fun main() {

    val coche1 = Coche(0)
    val lavadora1 = Lavadora()
    val telefono1 = Telefono()

    println("COCHE:\n")
    println("Acelerando 20 km/h...")
    coche1.acelerar(20)
    println("Encendiendo motor...")
    coche1.encender()
    println("Acelerando 20 km/h...")
    coche1.acelerar(20)
    println("Velocidad actual: ${coche1.kmHora}")
    println("Frenando 30 km/h...")
    coche1.frenar(30)
    println("Velocidad actual: ${coche1.kmHora}")
    println("Apagando motor...")
    coche1.apagar()
    println("Estado del motor: ${coche1.motorEncendido}")

    println("LAVADORA:\n")
    println("Estado de la lavadora: ${lavadora1.encendido}")
    println("Encendiendo lavadora...")
    lavadora1.encender()
    println("Estado de la lavadora: ${lavadora1.encendido}")
    println("Apagando lavadora...")
    lavadora1.apagar()
    println("Estado de la lavadora: ${lavadora1.encendido}")

    println("TElÉFONO:\n")
    println("Estado del teléfono: ${telefono1.encendido}")
    println("Encendiendo teléfono...")
    lavadora1.encender()
    println("Estado del teléfono: ${telefono1.encendido}")
    println("Apagando teléfono...")
    lavadora1.apagar()
    println("Estado del teléfono: ${telefono1.encendido}")
}